// dev-project-vue3/src/pages/events/index.vue
<template>
  <h3>
    This example shows how to pass events when using `applyReactInVue`.
  </h3>
  <ReactButton :foo="foo" @click="onClickForReact">
    <div class="slot">
      This is the Vue default slot
      <h4>
        current timestamp: {{currentTimestamp}}
      </h4>
      Click the button can refresh current timestamp<br/>
      <button @click="onClickForVue">button in Vue</button>
    </div>
  </ReactButton>
</template>

<script>
import { ref } from 'vue'
import { applyReactInVue } from 'veaury'
// This is a React Component
import ReactButton from "./react_app/Button"

export default {
  components: {
    ReactButton: applyReactInVue(ReactButton)
  },
  setup() {
    const currentTimestamp = ref(Date.now())
    const foo = ref(Math.random())
    function onClickForReact() {
      return foo.value = Math.random()
    }
    function onClickForVue() {
      return currentTimestamp.value = Date.now()
    }
    return {
      currentTimestamp,
      foo,
      onClickForReact,
      onClickForVue
    }
  }
}
</script>

<style scoped>
.slot {
  background: aquamarine;
  padding: 10px;
  margin: 10px;
}
</style>

// dev-project-react/src/components/Events/index.js
import { applyVueInReact } from 'veaury'
import BasicVue from './Basic'
import { useState } from 'react'

const Basic = applyVueInReact(BasicVue)
export default function () {
    const [state, setState] = useState({
        foo: Math.random(),
        currentTime: Date.now()
    })
    function onClickForVue() {
        setState((prevState) => ({
            ...prevState,
            foo: Math.random()
        }))
    }
    function onClickForReact() {
        setState((prevState) => ({
            ...prevState,
            currentTime: Date.now()
        }))
    }


    return <div>
        <h3>This example shows how to pass events when using `applyVueInReact`.</h3>
        <Basic foo={state.foo} onClick={onClickForVue}>
            <div className="slot">
                This is the Vue component Slot from React<br/>
                <span style={{fontWeight: 'bold'}}>current timestamp: {state.currentTime}</span><br/>
                Click the button can refresh current timestamp<br/>
                <button onClick={onClickForReact}>button in React</button>
            </div>
        </Basic>
    </div>
}
