// dev-project-vue3/src/pages/context/index.vue
<template>
  <h3>
    Vue components in slots can receive the context.<br/>
  </h3>
  The random number set in 'provide': <span style="color:red; font-weight: bold">{{random}}</span>
  <Basic>
    <div class="slot">
      This is the Vue default slot
      <Custom1/>
    </div>
  </Basic>
</template>

<script>
import { onMounted, onUnmounted, ref, provide } from 'vue'
import { applyPureReactInVue } from 'veaury'
// This is a React Component
import ReactBasic from "./react_app/Basic"
import Custom1 from "./Custom1"

export default {
  components: {
    Basic: applyPureReactInVue(ReactBasic),
    Custom1
  },
  setup() {
    let timer
    const random = ref(Math.random())
    provide('random', random)
    onMounted(() => {
      timer = setInterval(() => {
        random.value = Math.random()
      }, 1000)
    })
    onUnmounted(() => {
      clearInterval(timer)
    })
    return {
      random
    }
  }
}
</script>

<style scoped>
.slot {
  background: aquamarine;
  padding: 10px;
  margin: 10px;
}
</style>

// dev-project-react/src/components/Context/index.js
import {applyVueInReact} from 'veaury'
import BasicVue from './Basic'
import {useEffect, useState, useRef, createContext, useContext} from 'react'

const Basic = applyVueInReact(BasicVue)
const Context = createContext({})

function SubReactComponent() {
  const {bossName} = useContext(Context)
  return <div className="slot">bossName from Context: {bossName}</div>
}

export default function () {
  const [bossName, setBossName] = useState(Math.random)
  const timer = useRef(null)
  useEffect(() => {
    timer.current = setInterval(() => {
      setBossName(Math.random())
    }, 1000)
    return () => {
      clearInterval(timer.current)
    }
  }, [])
  return <div>
    <h3>This example shows the basic usage of `applyVueInReact`.</h3>
    <h4>Using React components in Vue components.</h4>
    <Context.Provider value={{bossName}}>
      <Basic>
        <div className="slot">
          This is the Vue component Slot from React<br/>
          <SubReactComponent/>
        </div>
      </Basic>
    </Context.Provider>
  </div>
}
